
- name: send_tx
  type: mutation
  return: response_send_tx
  params: request_send_tx
- name: get_tx
  type: query
  return: response_get_tx
  params: request_get_tx
- name: get_block
  type: query
  return: response_get_block
  params: request_get_block
- name: get_blocks
  type: query
  return: response_get_blocks
  params: request_get_blocks
- name: get_unconfirmed_txs
  type: query
  return: response_get_unconfirmed_txs
  params: request_get_unconfirmed_txs
- name: get_chain_info
  type: query
  return: response_get_chain_info
  params: request_get_chain_info
- name: get_node_info
  type: query
  return: response_get_node_info
  params: request_get_node_info
- name: get_net_info
  type: query
  return: response_get_net_info
  params: request_get_net_info
- name: get_validators_info
  type: query
  return: response_get_validators_info
  params: request_get_validators_info
- name: get_config
  type: query
  return: response_get_config
  params: request_get_config


- name: subscribe
  type: subscription
  return: response_subscribe
  params: request_subscribe
- name: unsubscribe
  type: mutation
  return: response_unsubscribe
  params: request_unsubscribe




- name: get_account_state
  type: query
  return: response_get_account_state
  params: request_get_account_state
- name: get_asset_state
  type: query
  return: response_get_asset_state
  params: request_get_asset_state
- name: get_stake_state
  type: query
  return: response_get_stake_state
  params: request_get_stake_state
- name: get_forge_state
  type: query
  return: response_get_forge_state
  params: request_get_forge_state




- name: get_forge_statistics
  type: query
  return: response_get_forge_statistics
  params: request_get_forge_statistics
- name: list_transactions
  type: query
  return: response_list_transactions
  params: request_list_transactions
- name: list_assets
  type: query
  return: response_list_assets
  params: request_list_assets
- name: list_stakes
  type: query
  return: response_list_stakes
  params: request_list_stakes
- name: list_top_accounts
  type: query
  return: response_list_top_accounts
  params: request_list_top_accounts
- name: list_asset_transactions
  type: query
  return: response_list_asset_transactions
  params: request_list_asset_transactions
- name: list_blocks
  type: query
  return: response_list_blocks
  params: request_list_blocks
- name: get_health_status
  type: query
  return: response_get_health_status
  params: request_get_health_status
